Repository 42mogle/42-mogle-backend, pull requests merged in 2022-12, with the labels that each got.

#44 fix:login_valid_password
  src/auth/auth.service.ts
Labels: bug

#51 Merge from Develop to Main
  src/attendance/attendance.controller.ts
  src/attendance/attendance.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/strategy/jwt.strategy.ts
  src/dbmanager/dbmanager.controller.ts
  src/dbmanager/dbmanager.service.ts
  src/operator/operator.controller.ts
  src/statistic/statistic.controller.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: enhancement

#53 feat: Set to use Configuration Module for environment variables
  .gitignore
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/auth/auth.service.ts
Labels: enhancement

#60 Fix/jwttokenuse
  src/attendance/attendance.controller.ts
  src/attendance/attendance.service.ts
  src/attendance/button.status.enum.ts
  src/attendance/dto/create-attendance.dto.ts
  src/auth/strategy/create-user.dto.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/jwtConstants.ts
  src/costom-decorator/get-userInfo.decorator.ts
  src/dbmanager/dbmanager.controller.ts
  src/dbmanager/dbmanager.service.ts
  src/operator/operator.controller.ts
  src/operator/operator.service.ts
  src/statistic/dto/attendanceStatus.dto.ts
  src/statistic/statistic.controller.ts
  src/statistic/statistic.service.ts
  src/user/dto/update-user.dto.ts
  src/user/user.controller.ts
  src/user/user.service.ts
Labels: bug

#63 fix: Modify ruleRegex in AuthService.checkPasswordValid() - #62
  src/auth/auth.service.ts
Labels: bug

#67 Feat/winstonlog
  package-lock.json
  package.json
  src/app.module.ts
  src/attendance/attendance.controller.ts
  src/attendance/attendance.service.ts
  src/auth/auth.controller.ts
  src/dbmanager/dbmanager.controller.ts
  src/dbmanager/dbmanager.service.ts
  src/operator/operator.controller.ts
  src/operator/operator.service.ts
  src/statistic/statistic.controller.ts
  src/user/user.controller.ts
Labels: enhancement

#69 fix: Set TypeOrmConfig being able to use env variables - close #68
  package-lock.json
  package.json
  src/app.module.ts
  src/configs/typeorm.config.ts
Labels: bug

#71 Feat/operating db
  src/app.controller.ts
  src/app.service.ts
  src/attendance/attendance.module.ts
  src/attendance/attendance.service.ts
  src/dbmanager/dbmanager.service.ts
  src/operator/dto/gsheetAttendance.dto.ts
  src/operator/operator.controller.ts
  src/operator/operator.module.ts
  src/operator/operator.service.ts
  src/statistic/statistic.service.ts
  src/user/user.module.ts
Labels: enhancement

#75 Feature/update month info property
  src/dbmanager/dbmanager.service.ts
  src/operator/operator.controller.ts
  src/operator/operator.service.ts
  src/statistic/statistic.service.ts
Labels: enhancement

#77 fix:winstonlog save
  package-lock.json
  package.json
  src/app.module.ts
  src/attendance/attendance.controller.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/configs/typeorm.config.ts
  src/dbmanager/dbmanager.controller.ts
  src/dbmanager/dbmanager.service.ts
  src/main.ts
  src/operator/operator.controller.ts
  src/operator/operator.service.ts
  src/statistic/statistic.controller.ts
Labels: bug, enhancement
